### ISSUE TITLE
Link context menu not closed when link panel is opened

### ISSUE THREAD

**Issue by thet** [Patternslib/pat-tiptap#31]
When creating a link and then clicking on "edit"‌ in the link context menu, the link panel (modal)‌ is opened but the context menu (pat-tooltip) is not closed:

![Screenshot from 2022-07-12 18-43-54](https://user-images.githubusercontent.com/170891/178548432-ae5b3545-242b-414c-b117-82ad0394bccc.png)

In a previous version, after closing the link panel, not everything from that panel was closed (I can't reproduce this issue with tiptap on the ``link-panel-fixes`` branch, so it might have gone):

![Screenshot from 2022-07-11 19-03-45](https://user-images.githubusercontent.com/170891/178548484-54c38a0a-bbcb-4b5c-b463-b1e6919ba334.png)

**Comment by thet** [comment]
Fixed on: https://thet.alita.ext0.syslab.com/workspaces/open-plaza/tiptaptest

**Comment by angeldasangel** [comment]
That works fine now: QA done ;)
